name: Publish
description: Publish Go Driver Release
inputs:
  version:
    description: The published version
    required: true
  prev_version:
    description: The previous version
    required: true
  silk_asset_group:
    description: The Silk Asset Group
    required: true
  push_changes:
    description: Whether to push the changes
    default: "true"
  token:
    description: The GitHub token
runs:
  using: composite
  steps:
    - uses: mongodb-labs/drivers-github-tools/full-report@v2
      with:
        product_name: mongo-go-driver
        release_version: ${{ inputs.version }}
        silk_asset_group: ${{ inputs.silk_asset_group }}
        security_report_location: ${{ env.SECURITY_REPORT_URL }}
        token: ${{ inputs.token }}
    - name: Publish GitHub Release
      shell: bash -eux {0}
      working-directory: ${{ github.action_path }}
      env:
        VERSION: ${{ inputs.version }}
        PREV_VERSION: ${{ inputs.prev_version }}
        PUSH_CHANGES: ${{ inputs.push_changes }}
        GH_TOKEN: ${{ inputs.token }}
      run: ./publish.sh
    - name: Upload S3 assets
      uses: mongodb-labs/drivers-github-tools/upload-s3-assets@v2
      with:
          version: ${{ inputs.version }}
          product_name: mongo-go-driver
          dry_run: ${{ env.DRY_RUN }}