name: Pre Publish
description: Pre Publish Action for Go Driver
inputs:
  version:
    description: The published version
    required: true
  push_changes:
    description: Whether to push the changes
    default: "true"

runs:
  using: composite
  steps:
    - name: Set up environment
      shell: bash
      run:
         bash ${{ github.action_path }}/set-environment.sh
      env:
        VERSION: "${{ inputs.version }}"
    - uses: mongodb-labs/drivers-github-tools/bump-version@v2
      with:
        version: ${{ inputs.version }}
        version_bump_script: "go run ${{ github.action_path }}/bump-version.go"
        commit_template: "${{ env.COMMIT_TEMPLATE }}"
        push_commit: ${{ inputs.push_changes }}
    - uses: mongodb-labs/drivers-github-tools/tag-version@v2
      with:
        version: "${{ env.TAG_VERSION }}"
        push_tag: ${{ inputs.push_changes }}