name: Update Tag

on:
  workflow_dispatch:

jobs:
  update-tag:
    name: Update Tag
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          # Needed to push the tag in the final step
          persist-credentials: true

      - name: Set up git config
        run: |
          git config user.email "167856002+mongodb-dbx-release-bot[bot]@users.noreply.github.com"
          git config user.name "mongodb-dbx-release-bot[bot]"

      - name: Remove the existing tag
        run: |
          export VERSION=$(cat .github/workflows/version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          git push origin ":v${VERSION}" || true

      - name: Create a new signed tag
        uses: ./git-sign
        with:
          command: git tag -a \"v${{ env.VERSION }}\" -m \"Update tag\" -s --local-user=${{ SECRETS.GPG_KEY_ID }}

      - name: Push the tag
        run:
            git push origin --tags